server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true     #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh1 #路由的ID，没有固定规则，但是要求唯一，建议配合服务名
          # uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #动态路由，匹配后提供服务的路由地址
          # 需要注意的是uri的协议为lb，表示启用Gateway的负载均衡功能。 lb://微服务名  是spring cloud gateway在微服务
          # 中自动为我们创建的负载均衡uri
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由

        - id: payment_routh2
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service #动态路由，匹配后提供服务的路由地址
#          filters:
#            - AddRequestParameter=X-Request-Id,1024 #过滤工厂会在匹配的请求头上加以对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/lb/**       #这个路径的才匹配
            - After=2021-05-14T10:01:02.143+08:00[Asia/Shanghai]  #这个时间点之后的请求才有效
            - Before=2021-06-14T10:01:02.143+08:00[Asia/Shanghai]  #这个时间点之前的请求才有效
            #- Between=2021-05-14T10:01:02.143+08:00[Asia/Shanghai],2021-06-14T10:01:02.143+08:00[Asia/Shanghai] #这两个时间点之间的请求有效
            - Cookie=username,echo  # cookie中的username属性中包含 正则表达式中定义的echo，请求才会有效
            #- Header=X-Request-Id, \d+ #请求头中有X-Request-Id这个参数，而且该参数的值满足定义的正则表达式，请求才会有效
            - Host=**.echo.com    #请求中携带匹配该规则的主机名时，本次请求才有效
            - Method=GET  #get请求才允许访问
            - Query=username, \d+ #要有参数名username且值满足后面定义的正则表达式的，该请求才有效
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
