server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EEEEEEcho/spring-cloud-config.git # git仓库的位置
          search-paths:   #搜索配置文件的目录
            - configs
      label: master       #分支

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
