server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: s814466057
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-provider
mybatis:
  type-aliases-package: com.echo.service.pojo
  mapper-locations: classpath:mybatis/mappers/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15