server:
  port: 80

spring:
  # zipkin配置
  zipkin:
    # 监控地址
    base-url: http://localhost:9411
    sleuth:
      sampler: #采样率，介于0 到 1之间，1则表示全部采样
        probability: 1

eureka:
  client:
    register-with-eureka: false #不把它注册到eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
# 设置Feign客户端超时时间(OpenFeign默认支持Ribbon)
ribbon:
  # 指的是建立连接所用时间，适用于网络状况正常的情况下，两端连接所需要的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    # feign日志，以什么级别，监视哪个接口(以debug方式监控PaymentFeignService接口)
    com.echo.service.PaymentFeignService: debug