server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: s814466057
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-provider  #作为微服务的名称
mybatis:
  type-aliases-package: com.echo.service.pojo
  mapper-locations: classpath:mybatis/mappers/**/*.xml
eureka: # 配置eureka，将服务注册进eureka
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka