server:
  port: 10086
spring:
  application:
    name: echo-eureka #将来作为微服务名称注入到eureka注册中心，eureka本身也会作为微服务进行注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
