server:
  port: 8006

spring:
  application:
    name: cloud-payment-service
###consul注册中心地址###
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包，用的是spring的jdbc
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: s814466057

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.echo.pojo     #配置所有别名的包的位置，意思就是com.echo.pojo.Payment可以直接写