server:
  port: 8001
  tomcat:
    max-threads: 1000

spring:
  application:
    name: cloud-provider-hystrix-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包，用的是spring的jdbc
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: s814466057

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.echo.pojo     #配置所有别名的包的位置，意思就是com.echo.pojo.Payment可以直接写成Payment

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/