server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.45.135:1111 #通过nginx反向代理的nacos的地址
      #server-addr: localhost:8848 #本地服务注册中心
management:
  endpoints:
    web:
      exposure:
        include: '*'
